export const MOCK_CONTACTS = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    lastMessage: 'Can you send me those design files?',
    time: '10:23 AM',
    unread: 2,
    status: 'online' as const,
  },
  {
    id: '2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    lastMessage: 'I\'ll be there in 5 minutes',
    time: 'Yesterday',
    unread: 0,
    status: 'offline' as const,
  },
  {
    id: '3',
    name: 'Carol Williams',
    email: 'carol@example.com',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    lastMessage: 'The meeting is confirmed for tomorrow',
    time: 'Yesterday',
    unread: 3,
    status: 'online' as const,
  },
  {
    id: '4',
    name: 'Dave Brown',
    email: 'dave@example.com',
    avatar: 'https://images.pexels.com/photos/1121796/pexels-photo-1121796.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    lastMessage: 'Check out this new article',
    time: 'Tuesday',
    unread: 0,
    status: 'away' as const,
  },
  {
    id: '5',
    name: 'Eve Davis',
    email: 'eve@example.com',
    avatar: 'https://images.pexels.com/photos/1382731/pexels-photo-1382731.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    lastMessage: 'Thanks for your help!',
    time: 'Monday',
    unread: 0,
    status: 'offline' as const,
  },
  {
    id: '6',
    name: 'Frank Miller',
    email: 'frank@example.com',
    avatar: 'https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    lastMessage: 'Did you see the game last night?',
    time: 'Sunday',
    unread: 1,
    status: 'online' as const,
  },
  {
    id: '7',
    name: 'Grace Wilson',
    email: 'grace@example.com',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    lastMessage: 'The project deadline has been extended',
    time: 'Last week',
    unread: 0,
    status: 'offline' as const,
  },
  {
    id: '8',
    name: 'Henry Taylor',
    email: 'henry@example.com',
    avatar: 'https://images.pexels.com/photos/846741/pexels-photo-846741.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    lastMessage: 'Can we reschedule our meeting?',
    time: 'Last week',
    unread: 0,
    status: 'away' as const,
  },
];

export const MOCK_MESSAGES = [
  {
    id: 'msg1',
    senderId: '1',
    text: 'Hey there! How are you doing today?',
    timestamp: '2023-05-01T09:30:00Z',
    status: 'read',
  },
  {
    id: 'msg2',
    senderId: 'me',
    text: 'I\'m doing well, thanks for asking! Just working on some new designs.',
    timestamp: '2023-05-01T09:32:00Z',
    status: 'read',
  },
  {
    id: 'msg3',
    senderId: '1',
    text: 'That sounds exciting! Can you send me those design files when you\'re done?',
    timestamp: '2023-05-01T09:35:00Z',
    status: 'read',
  },
  {
    id: 'msg4',
    senderId: 'me',
    text: 'Sure thing! I should be able to finish them by this afternoon.',
    timestamp: '2023-05-01T09:37:00Z',
    status: 'read',
  },
  {
    id: 'msg5',
    senderId: '1',
    text: 'Perfect! Looking forward to seeing them.',
    timestamp: '2023-05-01T09:40:00Z',
    status: 'read',
  },
  {
    id: 'msg6',
    senderId: 'me',
    text: 'Also, do you want me to include the color variations we discussed last week?',
    timestamp: '2023-05-01T09:45:00Z',
    status: 'read',
  },
  {
    id: 'msg7',
    senderId: '1',
    text: 'Yes, please include those. The client specifically asked about seeing different color options.',
    timestamp: '2023-05-01T09:47:00Z',
    status: 'read',
  },
  {
    id: 'msg8',
    senderId: 'me',
    text: 'Got it. I\'ll prepare those as well.',
    timestamp: '2023-05-01T09:50:00Z',
    status: 'read',
  },
];